import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          h2{
          font-size:38px;
          }
          h3{
          font-size:28px;
          }
          
          `
        }
      </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      


      </Head>
      <main >
        <div className={styles.container}>
          <div>
          <Image className={styles.myImage}  src="/new.avif" width={237} height={158} alt="imageholder"/>
          </div>
          <h1 className={styles.title}>
            <span>&lt;Hunting Coder/&gt;</span></h1>
          
          <div >
          <h2 className={styles.h2}>Latest Blogs</h2>
            <div className={styles.blogs}>  
                <h3 className={styles.h3}>How to learn javascript in 2024?</h3>
                <p className={styles.para}>Javascript is the language used to design logic for web</p>
            
            
                <h3 className={styles.h3}>How to learn javascript in 2024?</h3>
                 <p className={styles.para}>Javascript is the language used to design logic for web</p>

            
            
            <h3 className={styles.h3}>How to learn javascript in 2024?</h3>
             <p className={styles.para}>Javascript is the language used to design logic for web</p>

        </div>
      
        </div>
        </div>
      </main>
    </div>
  );
}
